export const PREDBLINK_ABI = [
  {
    name: 'marketCount',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'getMarketCore',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [
      { name: 'marketType', type: 'uint8' },
      { name: 'feedId', type: 'bytes32' },
      { name: 'targetValue', type: 'uint256' },
      { name: 'snapshotValue', type: 'uint256' },
      { name: 'endTime', type: 'uint256' },
      { name: 'endBlock', type: 'uint256' },
      { name: 'status', type: 'uint8' },
      { name: 'resolvedValue', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'getMarketQuestion',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ name: '', type: 'string' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'tweetMeta',
    inputs: [{ name: '', type: 'uint256' }],
    outputs: [
      { name: 'tweetId', type: 'string' },
      { name: 'authorHandle', type: 'string' },
      { name: 'authorName', type: 'string' },
      { name: 'tweetText', type: 'string' },
      { name: 'avatarUrl', type: 'string' },
      { name: 'metric', type: 'uint8' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'getYesPriceCents',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'getNoPriceCents',
    inputs: [{ name: 'id', type: 'uint256' }],
    outputs: [{ name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    name: 'buyYes',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'usdcAmount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    name: 'buyNo',
    inputs: [
      { name: 'id', type: 'uint256' },
      { name: 'usdcAmount', type: 'uint256' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
];
